---
## Install temporary directory
opendj_install: "/tmp/opendj_install"

# Initial password for Directory Manager
opendj_dm_password: "P@S5w0rd"

## OpenDJ install parameters
opendj_root: "/opt/opendj"
opendj_bin: "{{ opendj_root }}/bin"
opendj_config: "{{ opendj_root }}/config"
opendj_logs: "{{ opendj_root }}/logs"
opendj_context: "dc=team-tl,dc=intranet"
opendj_port_ldap: '1389'
opendj_port_ldaps: '1636'
opendj_port_admin: '4444'
opendj_port_replica: '8989'
opendj_user: "opendj"
opendj_group: "opendj"
opendj_dm_password_file: "/home/{{ opendj_user }}/.pwd"

## common part for dsconfig command
dsconfig_common: "--bindDN 'cn=Directory Manager' --port 4444 --bindPasswordFile {{ opendj_dm_password_file }} --trustAll --no-prompt"

# Packages
opendj_version: "4.4.10"
opendj_package_deb: "opendj_{{ opendj_version }}-1_all.deb"
opendj_package_rpm: "opendj-{{ opendj_version }}-1.noarch.rpm"
opendj_package_zip: "opendj-{{ opendj_version }}.zip"
opendj_url: "https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/{{ opendj_version }}"
opendj_url_deb: "{{ opendj_url }}/{{ opendj_package_deb }}"
opendj_url_rpm: "{{ opendj_url }}/{{ opendj_package_rpm }}"
opendj_url_zip: "{{ opendj_url }}/{{ opendj_package_zip }}"

