---
packages_specific:
  - openjdk-11-jdk

# ------------------ OpenDJ --------------------
## Selfsign or signed certificates
opendj_selfsign: false

## Install temporary directory
opendj_install: "/tmp/opendj_install"

# Initial password for Directory Manager
opendj_dm_password: "P@S5w0rd"

## OpenDJ install parameters
opendj_opt: "/opt"
opendj_root: "{{ opendj_opt }}/opendj"
opendj_bin: "{{ opendj_root }}/bin"
opendj_config: "{{ opendj_root }}/config"
opendj_logs: "{{ opendj_root }}/logs"
opendj_port_ldap: '1389'
opendj_port_ldaps: '1636'
opendj_port_admin: '4444'
opendj_port_replica: '8989'
opendj_user: "opendj"
opendj_group: "opendj"
opendj_dm_password_file: "/opt/opendj/.pwd"

## common part for dsconfig command
opendj_dsconfig: "--bindDN 'cn=Directory Manager' --port 4444 --bindPasswordFile {{ opendj_dm_password_file }} --trustAll --no-prompt"

# Packages
opendj_version: "4.4.11"
opendj_package_deb: "opendj_{{ opendj_version }}-1_all.deb"
opendj_url: "https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/{{ opendj_version }}"
opendj_url_deb: "{{ opendj_url }}/{{ opendj_package_deb }}"

# Replication parameters
opendj_replica_hostname: "ldap167.{{ domain_name }}"
opendj_replica_dm_password: "P@S5w0rd"
opendj_replica_dm_password_file: "/home/{{ opendj_user }}/.pwddm"
opendj_replica_admin_password: "P@S5w0rd"
opendj_replica_admin_password_file: "/home/{{ opendj_user }}/.pwdadm"

