---
packages_specific:
  - haproxy
  - openjdk-11-jre-headless

# ------------------ OpenDJ --------------------
## Selfsign or signed certificates
opendj_selfsign: false

## Install temporary directory
opendj_install: "/tmp/opendj_install"

# Initial password for Directory Manager
opendj_dm_password: "P@S5w0rd"

## OpenDJ install parameters
opendj_opt: "/opt"
opendj_root: "{{ opendj_opt }}/opendj"
opendj_bin: "{{ opendj_root }}/bin"
opendj_config: "{{ opendj_root }}/config"
opendj_logs: "{{ opendj_root }}/logs"
opendj_context: "dc=team-tl,dc=intranet"
opendj_port_ldap: '1389'
opendj_port_ldaps: '1636'
opendj_port_admin: '4444'
opendj_port_replica: '8989'
opendj_user: "opendj"
opendj_group: "opendj"
opendj_dm_password_file: "/home/{{ opendj_user }}/.pwd"

## common part for dsconfig command
opendj_dsconfig: "--bindDN 'cn=Directory Manager' --port 4444 --bindPasswordFile {{ opendj_dm_password_file }} --trustAll --no-prompt"

# Packages
opendj_version: "4.4.11"
opendj_package_zip: "opendj-{{ opendj_version }}.zip"
opendj_url: "https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/{{ opendj_version }}"
opendj_url_zip: "{{ opendj_url }}/{{ opendj_package_zip }}"
opendj_openjdk: "openjdk-11-jdk"

# Replication parameters
opendj_replica_hostname: ldap167.team-tl.intranet
opendj_replica_dm_password: "P@S5w0rd"
opendj_replica_dm_password_file: "/home/{{ opendj_user }}/.pwddm"
opendj_replica_admin_password: "P@S5w0rd"
opendj_replica_admin_password_file: "/home/{{ opendj_user }}/.pwdadm"

# ------------------ HA Keepalived ------------------------
keepalive_trackname: "track_opendj"
keepalive_process: "haproxy"
keepalive_id: 197
keepalive_advert: '1'
keepalive_password: "p@S5f0rD"
keepalive_vip: "192.168.0.197"

