---
- name: 5.1 Enable firewall
  systemd:
    state: started
    name: firewalld
    enabled: yes
    masked: no
  become: true

- name: 5.2 Open ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  with_items:
    - "389/tcp"
    - "636/tcp"
    - "{{ opendj_port_admin }}/tcp"
    - "{{ opendj_port_replica }}/tcp"

- name: 5.3 Port forwards 389 and 636 to {{ opendj_port_ldap }} and {{ opendj_port_ldaps }} for incoming connection
  firewalld:
    rich_rule: "rule family=ipv4 forward-port port={{ item.from }} protocol=tcp to-port={{ item.to }}"
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  with_items:
    - { from: '389', to: "{{ opendj_port_ldap }}" }
    - { from: '636', to: "{{ opendj_port_ldaps }}" }

- name: 5.3 Port forwards 389 and 636 to {{ opendj_port_ldap }} and {{ opendj_port_ldaps }} for incoming connection - in future
  firewalld:
    port_forward:
      - port: "{{ item.from }}"
      - proto: tcp
      - toport: "{{ item.to }}"
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  with_items:
    - { from: '389', to: "{{ opendj_port_ldap }}" }
    - { from: '636', to: "{{ opendj_port_ldaps }}" }
  when: ansible_version.full == "5.0.0"

- name: 5.4 Add access for local connection
  command: "firewall-cmd
            --permanent
            --direct
            --add-rule ipv4 nat OUTPUT 0 -p tcp -o lo
            --dport {{ item.from }} -j REDIRECT --to-ports {{ item.to }}"
  become: true
  with_items:
    - { from: '389', to: "{{ opendj_port_ldap }}" }
    - { from: '636', to: "{{ opendj_port_ldaps }}" }

- name: 5.5 Reload firewall rules
  systemd:
    state: reloaded
    name: firewalld
    enabled: yes
    masked: no
  become: true

