---
- name: 4.1 Change ads-keystore part 1
  command: su - {{ opendj_user }} -c "{{ opendj_bin }}/dsreplication set-cert
        --hostname {{ ansible_hostname }}
        --port 4444
        --replCertNickName ads-certificate
        --replKeyStoreType PKCS12
        --replKeyStorePath {{ opendj_install }}/certs/ads-keystore
        --replKeyStorePasswordFile {{ opendj_install }}/certs/ads-keystore.pin
        --adminUID admin
        --adminPasswordFile {{ opendj_replica_admin_password_file }}
        --trustStorePath {{ opendj_config }}/admin-truststore
        --no-prompt"
  become: true

- name: 4.2 Copy ads-keystore into config directory
  copy:
    src: "{{ opendj_install }}/certs/{{ item.file }}"
    dest: "{{  opendj_config  }}"
    mode: "{{ item.mode }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    remote_src: yes
  become: true
  with_items:
      - { file: "ads-keystore", mode: "0640" }
      - { file: "ads-keystore.pin", mode: "0600" }

- name: 4.3 Change ads-keystore part 2
  command: su - {{ opendj_user }} -c "{{ opendj_bin }}/dsreplication set-cert
        --hostname {{ ansible_fqdn }}
        --port 4444
        --replCertNickName ads-certificate
        --replKeyStoreType PKCS12
        --replKeyStorePath {{ opendj_install }}/certs/ads-keystore
        --replKeyStorePasswordFile {{ opendj_install }}/certs/ads-keystore.pin
        --adminUID admin
        --adminPasswordFile {{ opendj_replica_admin_password_file }}
        --trustStorePath {{ opendj_config }}/admin-truststore
        --no-prompt"
  become: true

