---
- name: 5.1 install required Samba packages
  apt:
    name:
      - krb5-user
      - samba
      - smbclient
      - winbind
    state: present
  when:
    - samba_install == "true"

- name: 5.2 disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  with_items:
    - systemd-resolved
    - smbd
    - nmbd
    - winbind
  when:
    - samba_install == "true"

- name: 5.3 remove old files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/resolv.conf
    - /var/lib/samba/private/krb5.conf
    - /etc/samba/smb.conf

- name: 5.4 templates
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - krb5.conf
    - resolv.conf
  when:
    - samba_install == "true"

- name: 5.5 symlinks for krb5.conf
  ansible.builtin.file:
    src: "/etc/krb5.conf"
    dest: "/var/lib/samba/private/krb5.conf"
    state: link

- name: 5.6 open firewall Ubuntu
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: 137, proto: "udp" }
    - { port: 138, proto: "udp" }
    - { port: 139, proto: "tcp" }
    - { port: 445, proto: "tcp" }
    - { port: 88,  proto: "tcp" }
    - { port: 88,  proto: "udp" }
    - { port: 53,  proto: "tcp" }
    - { port: 53,  proto: "udp" }
    - { port: 636, proto: "tcp" }
  when: 
    - ansible_os_family == "Debian"
    - samba_install == "true"

- name: 5.7 Provision AD domain
  shell: 'samba-tool domain provision
      --server-role=dc
      --use-rfc2307
      --dns-backend=SAMBA_INTERNAL
      --realm={{ domain_name | upper }}
      --domain={{ domain | upper }}
      --adminpass=={{ samba_password_administrator }}'
  when:
    - samba_install == "true"
    - samba_dc_first == "true"

- name: 5.8 Add new controller
  shell: 'samba-tool domain join
      {{ domain_name | upper }} 
      DC 
      -U "{{ ansible_hostname }}\administrator"
      --adminpass={{ samba_password_administrator }}
      --dns-backend=SAMBA_INTERNAL
      --option="dns forwarder={{ samba_first_dc_ip }}"
      --option="idmap_ldb:use rfc2307 = yes"'
  when:
    - samba_install == "true"
    - samba_dc_next == "true"

- name: 5.9 Add dns-forwarder into smb.conf
  ansible.builtin.lineinfile:
    path: /etc/samba/smb.conf
    search_string: '<FilesMatch ".php[45]?$">'
    insertafter: '^\[global\]'
    line: "    dns forwarder = {{ default_dns }}"
    backup: yes
  when:
    - samba_install == "true"
    - samba_dc_first == "true"

- name: 5.10 Add TLS into samba.conf
  ansible.builtin.lineinfile:
    path: /etc/samba/smb.conf
    search_string: '<FilesMatch ".php[45]?$">'
    insertafter: '^\[global\]'
    line: "    {{ item }}"
    backup: yes
  with_items:
    - "tls keyfile  = tls/key.pem"
    - "tls certfile = tls/cert.pem"
    - "tls cafile   = tls/ca.pem"
    - "tls enabled  = yes"
  when: 
    - samba_install == "true"

- name: 5.11 symlinks for certs
  ansible.builtin.file:
    src: "/etc/ssl/{{ item.src }}"
    dest: "/var/lib/samba/private/tls/{{ item.dest }}"
    state: link
  with_items:
    - { src: "private/privkey.pem",              dest: "key.pem" }
    - { src: "certs/{{ ansible_hostname }}.pem", dest: "cert.pem" }
    - { src: "certs/ca.pem",                     dest: "cert.pem" }
  when: 
    - samba_install == "true"

- name: 5.12 enable and start Samba AD
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: started
    enabled: true
    masked: false
  when:
    - samba_install == "true"
