---
- name: 1 Install Cockpit OracleLinux
  yum:
    name: cockpit-ws
    state: present
  become: true
  when: ansible_distribution == "OracleLinux"
  notify: "restart cockpit daemon"

- name: 1 Install Cockpit Ubuntu
  apt:
    name: cockpit-ws
    state: present
  when: ansible_distribution == "Ubuntu"
  notify: "restart cockpit daemon"

- name: 2 Remove old certificates
  file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items:
    - "/etc/cockpit/ws-certs.d/0-self-signed-ca.pem"
    - "/etc/cockpit/ws-certs.d/0-self-signed.cert"

#- name: 3 Copy certificates
#  copy:
#    src: "{{ ansible_hostname }}.crt"
#    dest: "/etc/cockpit/ws-certs.d/{{ ansible_hostname }}.crt"
#    mode: '0644'
#    owner: root
#    group: cockpit-ws
#  become: true
#  notify: "restart cockpit daemon"

- name: 3 Copy certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/cockpit/ws-certs.d/{{ item }}"
    mode: '0644'
    owner: root
    group: cockpit-ws
  become: true
  notify: "restart cockpit daemon"
  with_items:
    - "{{ ansible_hostname }}.crt"
    - "ca.pem"

