---
#--------------------------------------------
#-  SERVER
#--------------------------------------------
- name: 2.1 install Zabbix server
  apt:
    name: "{{ zabbix_server_packages }}"
    update_cache: yes
    state: present
  when: zabbix_server == " yes"
  notify: zabbix-server-restarted

- name: 2.2 configure server
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_server.conf"
    regexp: '{{ item.regex }}'
    line:   '\g<1>{{ item.line }}'
    backup: yes
    backrefs: yes
  with_items:
  - { regex: '^# (DBHost=).*',     line: '{{ zabbix_db_host }}' }
  - { regex: '^# (DBPort=).*',     line: '{{ zabbix_db_port }}' }
  - { regex: '^(DBName=).*',       line: '{{ zabbix_db_db }}' }
  - { regex: '^(DBUser=).*',       line: '{{ zabbix_db_user }}' }
  - { regex: '^# (DBPassword=).*', line: '{{ zabbix_db_passwd }}' }
  - { regex: '^# (ListenIP=).*',   line: '0.0.0.0' }
  when: zabbix_server == " yes"
  notify: zabbix-server-restarted

