---
- name: 1 install repo Zabbix
  apt:
    deb: "{{ zabbix_url_deb }}"
    state: present

- name: 2 install Zabbix agent
  apt:
    name: "{{ zabbix_agent_packages }}"
    update_cache: yes
    state: present
  when: zabbix_host == "agent"

- name: 3 install Zabbix server
  apt:
    name: "{{ zabbix_server_packages }}"
    update_cache: yes
    state: present
  when: zabbix_host == "server"

- name: 4 configure agent
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    regexp: '{{ item.regex }}'
    line:   '\g<1>{{ item.line }}'
    backup: yes
    backrefs: yes
  with_items:
    - { regex: '^(Server=).*',       line: '192.168.0.0/24' }
    - { regex: '^(Hostname=).*',     line: '{{ ansible_fqdn }}' }
    - { regex: '^(ServerActive=).*', line: '192.168.0.167,192.168.0.177' }

- name: 5 start Zabbix agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
    masked: no

- name: 6 configure server
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_server.conf"
    regexp: '{{ item.regex }}'
    line:   '\g<1>{{ item.line }}'
    backup: yes
    backrefs: yes
  with_items:
  - { regex: '^# (DBHost=).*',     line: '{{ zabbix_db_host }}' }
  - { regex: '^# (DBPort=).*',     line: '{{ zabbix_db_port }}' }
  - { regex: '^(DBName=).*',       line: '{{ zabbix_db_db }}' }
  - { regex: '^(DBUser=).*',       line: '{{ zabbix_db_user }}' }
  - { regex: '^# (DBPassword=).*', line: '{{ zabbix_db_passwd }}' }
  - { regex: '^# (ListenIP=).*',   line: '0.0.0.0' }
  when: zabbix_host == "server"

- name: 7 start Zabbix server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
    enabled: yes
    masked: no

- name: 8 copy GUI config
  copy:
    src: /usr/share/zabbix/conf/zabbix.conf.php.example
    dest: /etc/zabbix/web/zabbix.conf.php
    remote_src: yes
  when: zabbix_host == "server"

- name: 9 configure GUI
  ansible.builtin.replace:
    path: /etc/zabbix/web/zabbix.conf.php
    regexp: ^(.DB\['{{ item.regex }}'\]\t).*$
    replace: \1= '{{ item.line }}';
    backup: no
  with_items:
    - { regex: "SERVER",   line: '{{ zabbix_db_host }}' }
    - { regex: "PORT",     line: '{{ zabbix_db_port }}' }
    - { regex: "DATABASE", line: '{{ zabbix_db_db }}' }
    - { regex: "USER",     line: '{{ zabbix_db_user }}' }
    - { regex: "PASSWORD", line: '{{ zabbix_db_passwd }}' }
  when: zabbix_host == "server"

- name: 10 configure GUI
  ansible.builtin.replace:
    path: /etc/zabbix/web/zabbix.conf.php
    regexp: ^(\${{ item.regex }}\t).*$
    replace: \1= '{{ item.line }}';
    backup: no
  with_items:
    - { regex: "ZBX_SERVER",      line: '{{ zabbix_server }}' }
    - { regex: "ZBX_SERVER_NAME", line: '{{ ansible_hostname | upper }}' }
  when: zabbix_host == "server"

- name: 11 restart Apache server
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  when: zabbix_host == "server"

