---
- name: 1 install repo Zabbix
  apt:
    deb: "{{ zabbix_url_deb }}"
    state: present

- name: 2 install Zabbix agent
  apt:
    name: "{{ zabbix_agent_packages }}"
    update_cache: yes
    state: present
  when: zabbix_host == "agent"

- name: 3 install Zabbix server
  apt:
    name: "{{ zabbix_server_packages }}"
    update_cache: yes
    state: present
  when: zabbix_host == "server"

- name: 4 configure agent
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_agentd.conf"
    regexp: '{{ item.regex }}'
    line:   '\g<1>{{ item.line }}'
    backup: yes
    backrefs: yes
  with_items:
    - { regex: '^(Server=).*',   line: '192.168.0.0/24' }
    - { regex: '^(Hostname=).*', line: '{{ ansible_fqdn }}' }
    #ServerActive=127.0.0.1/192.168.0.167,192.168.0.177

- name: 5 configure server
  ansible.builtin.lineinfile:
    path: "/etc/zabbix/zabbix_server.conf"
    regexp: '{{ item.regex }}'
    line:   '\g<1>{{ item.line }}'
    backup: yes
    backrefs: yes
  with_items:
  - { regex: '^# (DBHost=).*',     line: '192.168.0.196' }
  - { regex: '^# (DBName=).*',     line: 'zabbix' }
  - { regex: '^# (DBUser=).*',     line: 'zabbix' }
  - { regex: '^# (DBPassword)=.*', line: 'Z@bbiks' }
  - { regex: '^# (ListenIP)=.*',   line: '0.0.0.0' }
  when: zabbix_host == "server"


#- name: create site dirs
#  file:
#    path: {{item}}
#    state: diretory

#- name: copy an index.html
#  template:
#    src: index.html.j2
#    dest: {{apache_docroot}}/index.html
#
#- name: copy an httpd.conf
#  template:
#    src: httpd.conf-{{ansible_os_family}}.j2
#    dest: {{apache_config}}
#    notify: restart apache

- name: start Zabbix agent
  systemd:
    name: zabbix-agent
    state: restarted
    enable: yes


