---
- name: 1 install Apache2, php etc.
  apt:
    name: "{{ packages }}"
    state: present

- name: 2 remove defaut index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: 3 copy defaut web content
  ansible.builtin.unarchive:
    src: web.tar.gz
    dest: /var/www/html
    owner: www-data
    group: www-data

