---
- name: 1.1 Create Install temporary directory
  file:
    path: "{{ opendj_install }}"
    owner: root
    group: root
    mode: '0775'
    state: directory

- name: 1.2 Install OpenDJ
  apt:
    deb: "{{ opendj_url_deb }}"
    state: present

#- name: 1.7 Create OpenDJ start script
#  command: "/opt/opendj/bin/create-rc-script -f /etc/init.d/opendj -u {{ opendj_user }}"
#  become: true
#
#- name: 1.8 Systemd daemon reload
#  ansible.builtin.systemd:
#    daemon_reload: yes
#  become: true

