---
- name: 1.1 Add opendj user
  user:
    name: "{{ opendj_user }}"
    comment: OpenDJ a LDAP daemon
    shell: "/bin/bash"
  become: true
  when: opendj_user != "root"

- name: 1.2 Add OpenDJ into PATH in .bashrc
  lineinfile:
    path: "/home/{{ opendj_user }}/.bashrc"
    line: "PATH={{ opendj_bin }}:$PATH"
    create: yes
  become: true

- name: 1.3 Create Install temporary directory
  file:
    path: "{{ opendj_install }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    mode: '0775'
    state: directory
  become: true

- name: 1.4 Download OpenDJ.zip for Linux
  get_url:
    url: "{{ opendj_url_zip }}"
    dest: "{{ opendj_install }}/{{ opendj_package_zip }}"
  become: true

- name: 1.5 Unpack OpenDJ zip package
  unarchive:
    src: "{{ opendj_install }}/{{ opendj_package_zip }}"
    dest: "{{ opendj_opt }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    remote_src: true
  become: true

- name: 1.6 Install OpenJDK
  apt:
    name: "{{ opendj_openjdk }}"
    state: present
  become: true

- name: 1.7 Create OpenDJ start script
  command: "/opt/opendj/bin/create-rc-script -f /etc/init.d/opendj -u {{ opendj_user }}"
  become: true

- name: 1.8 Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

