---
- name: 2.1 mkdir certs
  file:
    path: "{{ opendj_root }}/certs"
    owner: root
    group: root
    mode: '0750'
    state: directory
  become: true
  when: opendj_selfsign == false

- name: 2.2 Unzip keystores
  unarchive:
    src: "{{ ansible_hostname }}.zip"
    dest: "{{ opendj_root }}/certs"
    owner: root
    group: root
  become: true
  when: opendj_selfsign == false

- name: 2.3 OpenDJ directory ownership
  file:
    path: "{{ opendj_root }}"
    owner: root
    group: root
    recurse: true
  become: true

- name: 2.4 Directory Manager password
  copy:
    content: "{{ opendj_dm_password }}"
    dest: "{{ opendj_dm_password_file }}"
    owner: root
    group: root
    mode: '0600'
  become: true

