---
- name: 3.1 OpenDJ setup
  command: "{{ opendj_root }}/setup
           --cli
           --baseDN {{ opendj_context }}
           --addBaseEntry
           --ldapPort {{ opendj_port_ldap }}
           --adminConnectorPort {{ opendj_port_admin }}
           --rootUserDN 'cn=Directory Manager'
           --rootUserPasswordFile {{ opendj_dm_password_file }}
           --ldapsPort {{ opendj_port_ldaps }}
           --usePkcs12keyStore {{ opendj_root }}/certs/keystore
           --keySTorePasswordFile {{ opendj_root }}/certs/keystore.pin
           --certNickname server-cert
           --hostName {{ ansible_fqdn }}
           --noPropertiesFile
           --doNotStart
           --no-prompt"
  when: opendj_selfsign == false

- name: 3.2 OpenDJ setup
  command: "{{ opendj_root }}/setup
           --cli
           --baseDN {{ opendj_context }}
           --addBaseEntry
           --ldapPort {{ opendj_port_ldap }}
           --adminConnectorPort {{ opendj_port_admin }}
           --rootUserDN 'cn=Directory Manager'
           --rootUserPasswordFile {{ opendj_dm_password_file }}
           --ldapsPort {{ opendj_port_ldaps }}
           --generateSelfSignedCertificate
           --hostName {{ ansible_fqdn }}
           --noPropertiesFile
           --doNotStart
           --no-prompt"
  when: opendj_selfsign == true

- name: 3.3 My own schema extensions
  copy:
    src: "{{ item }}"
    dest: "{{ opendj_config }}/schema/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - 99-user.ldif

