---
- name: 4.1 Copy keystores
  copy:
    src: "{{ opendj_root }}/certs/{{ item.file }}"
    dest: "{{ opendj_config }}/{{ item.file }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    remote_src: true
  when: opendj_selfsign == false
  with_items:
    - { file: "keystore",           mode: '0640' }
    - { file: "admin-keystore",     mode: '0640' }
    - { file: "admin-truststore",   mode: '0640' }
    - { file: "admin-keystore.pin", mode: '0600' }
      #    - { file: "ads-keystore",       mode: '0640' }
      #    - { file: "ads-keystore.pin",   mode: '0600' }

- name: 4.2 Start OpenDJ
  command: "{{opendj_bin }}/start-ds"

- name: 4.3 Set keystore for user
  command: "{{opendj_bin }}/dsconfig
        set-key-manager-provider-prop
        --provider-name PKCS12
        --set key-store-file:config/keystore
        {{ opendj_dsconfig }}"
  when: opendj_selfsign == false

- name: 4.4 Set keystore for admin
  command: "{{opendj_bin }}/dsconfig
        set-key-manager-provider-prop
        --provider-name Administration
        --set key-store-type:PKCS12
        {{ opendj_dsconfig }}"
  when: opendj_selfsign == false

- name: 4.5 Set ads-truststore part 1
  command: "{{opendj_bin }}/dsconfig
          set-backend-prop
          --backend-name ads-truststore 
          --set trust-store-file:{{ opendj_root }}/certs/ads-truststore 
        {{ opendj_dsconfig }}"
  when: opendj_selfsign == false

- name: 4.6 Copy ads-truststore
  copy:
    src: "{{ opendj_root }}/certs/{{ item.file }}"
    dest: "{{ opendj_config }}/{{ item.file }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    remote_src: true
  when: opendj_selfsign == false
  with_items:
    - { file: "ads-truststore",     mode: '0640' }
    - { file: "ads-truststore.pin", mode: '0600' }

- name: 4.7 Set ads-truststore part 2
  command: "{{opendj_bin }}/dsconfig
          set-backend-prop
          --backend-name ads-truststore 
          --set trust-store-file:config/ads-truststore 
        {{ opendj_dsconfig }}"
  when: opendj_selfsign == false

