---
- name: 5.1 Open firewall via ufw
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  become: true
  when: ansible_distribution == "Ubuntu"
  with_items:
    - "{{ opendj_port_admin }}"
    - "{{ opendj_port_replica }}"
    - 389
    - 636
    - "{{ opendj_port_ldap }}"
    - "{{ opendj_port_ldaps }}"

- name: 5.2 Redirect ports 389 and 636 to {{ opendj_port_ldap }} and {{ opendj_port_ldaps }} with ufw
  ufw:
    rule: allow
    direction: in
    proto: tcp
    from_port: "{{ item.from }}"
    to_port: "{{ item.to }}"
    to_ip: 127.0.0.1
    state: reloaded
  become: true
  when: ansible_distribution == "Ubuntu"
  with_items:
    - { from: "389", to: "{{ opendj_port_ldap }}" }
    - { from: "636", to: "{{ opendj_port_ldaps }}" }

