---
- name: c.1 Remove certs directory
  file:
    path: "{{ opendj_root }}/certs"
    state: absent
  become: true

- name: c.2 Remove install directory
  file:
    path: "{{ opendj_install }}"
    state: absent
  become: true

