---
- name: 1.1 copy configs
  copy:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "vimrc",      dest: "/etc/skel/.vimrc",                    owner: "root", group: "root", mode: "644" }
    - { src: "vimrc",      dest: "/root/.vimrc",                        owner: "root", group: "root", mode: "644" }
    - { src: "vimrc",      dest: "/home/tlu/.vimrc",                    owner: "tlu",  group: "tlu",  mode: "644" }

- name: 1.2 apt update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: 1.3 install required common packages
  apt:
    name: "{{ packages_common }}"
    state: present

- name: 1.4 install required Samba packages
  apt:
    name:
      - samba
      - winbind
      - smbclient
    state: present
  when:
    - samba_install == "true"

- name: 1.5 Remove old certificates of Cockpit and default
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/cockpit/ws-certs.d/*"

- name: 1.6 copy certs
  copy:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { src: "ca.pem",                         dest: "/usr/local/share/ca-certificates/ca.crt", }
    - { src: "{{ ansible_hostname }}.crt",     dest: "/etc/ssl/{{ ansible_hostname }}.pem" }
    - { src: "{{ ansible_hostname }}-key.pem", dest: "/etc/ssl/private/privkey.pem" }
    - { src: "{{ ansible_hostname }}.pem",     dest: "/etc/ssl/certs/{{ ansible_hostname }}.pem"}

- name: 1.7 create symlinks certs for cockpit
  ansible.builtin.file:
    src: "/etc/ssl/{{ item.src }}"
    dest: "/etc/cockpit/ws-certs.d/{{ item.dest }}"
    state: link
  with_items:
    - { src: "private/privkey.pem",              dest: "{{ ansible_hostname }}.key" }
    - { src: "certs/{{ ansible_hostname }}.pem", dest: "{{ ansible_hostname }}.cert" }
  notify: "restart cockpit daemon"

- name: 1.8 update CA certs
  command: update-ca-certificates

