---
- name: 1.1 copy configs
  copy:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "vimrc",      dest: "/etc/skel/.vimrc",                    owner: "root", group: "root", mode: "644" }
    - { src: "vimrc",      dest: "/root/.vimrc",                        owner: "root", group: "root", mode: "644" }
    - { src: "vimrc",      dest: "/home/tlu/.vimrc",                    owner: "tlu",  group: "tlu",  mode: "644" }

- name: 1.2 apt update
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # one day

- name: 1.3 install required common packages
  apt:
    name: "{{ packages_common }}"
    state: present

- name: 1.4 install required specific packages
  apt:
    name: "{{ packages_specific }}"
    state: present

- name: 1.5 Remove old certificates of Cockpit
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cockpit/ws-certs.d/0-self-signed-ca.pem"
    - "/etc/cockpit/ws-certs.d/0-self-signed.cert"

- name: 1.6 Copy certificates
  copy:
    src: "{{ ansible_hostname }}.pem"
    dest: "/etc/cockpit/ws-certs.d/{{ ansible_hostname }}.cert"
    mode: '0644'
    owner: root
  notify: "restart cockpit daemon"

- name: 1.7 copy configs
  copy:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    owner: root
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - { src: "ca.pem",                         dest: "/usr/local/share/ca-certificates/ca.crt",             group: "root" }
    - { src: "{{ ansible_hostname }}.crt",     dest: "/etc/ssl/{{ ansible_hostname }}.crt",                 group: "root" }
    - { src: "{{ ansible_hostname }}.pem",     dest: "/etc/ssl/{{ ansible_hostname }}.pem",                 group: "root" }
    - { src: "{{ ansible_hostname }}.pem",     dest: "/etc/pki/{{ ansible_hostname }}.pem",                 group: "root" }
    - { src: "ca.pem",                         dest: "/etc/pki/ca.pem",                                     group: "root" }
    - { src: "{{ ansible_hostname }}-key.pem", dest: "/etc/ssl/private/privkey.pem",                        group: "root" }
    - { src: "{{ ansible_hostname }}.pem",     dest: "/etc/cockpit/ws-certs.d/{{ ansible_hostname }}.cert", group: "cockpit-ws" }

- name: 1.8 update CA certs
  command: update-ca-certificates
