---
- name: 3.1 Install DUF on Ubuntu
  apt:
    deb: "{{ duf_url_deb }}"
    state: present
  when: ansible_os_family == "Debian"

- name: 3.2 Install DUF on Oracle Linux
  yum:
    rpm: "{{ duf_url_rpm }}"
    state: present
  when: ansible_os_family == "RedHat"

