---
zabbix_db_host: 192.168.0.197
zabbix_db_db: zabbix
zabbix_db_port: 3306
zabbix_db_user: zabbix
zabbix_db_passwd: Z@bbiks
zabbix_server: 192.168.0.197

zabbix_version: '5.4'
zabbix_ubuntu: "{{ ansible_distribution_version }}"
zabbix_url_deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+ubuntu{{ zabbix_ubuntu }}_all.deb"

zabbix_agent_packages:
  - zabbix-agent

zabbix_server_packages:
  - zabbix-server-mysql

zabbix_gui_packages:
  - zabbix-apache-conf
  - zabbix-nginx-conf
  - zabbix-frontend-php
  - php7.4
  - php7.4-bcmath
  - php7.4-fpm
  - php7.4-gd
  - php7.4-gettext
  - php7.4-json
  - php7.4-ldap
  - php7.4-mbstring
  - php7.4-mysql
  - php-net-socket
  - php-pear
  - php7.4-xml
    #- php7.4-ctype
    #- php7.4-libxml
    #- php7.4-session
    #- php7.4-openssl
    #- php7.4-socket
    #- php7.4-xmlreader
    #- php7.4-xmlwriter

