---
- name: 1.1 Install keepalived on Ubuntu
  apt:
    name: keepalived
    state: present
  when: ansible_os_family == "Debian"

- name: 1.1 Install keepalived on Oracle Linux
  yum:
    name: keepalived
    state: present
  when: ansible_os_family == "RedHat"

- ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: 1.3 Copy keepalive.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    owner: root
    group: root

- name: 1.4.1 Open port 112 in firewall in Ubuntu
  ufw:
    rule: allow
    src: 224.0.0.18
  when: ansible_os_family == "Debian"

- name: 1.4.2 Open port 112 in firewall in Ubuntu
  ufw:
    rule: allow
    dest: 224.0.0.18
  when: ansible_os_family == "Debian"

- name: 1.4 Open port 112 in firewall in OracleLinux
  firewalld:
    rich_rule: rule protocol value="vrrp" accept
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_os_family == "RedHat"

- name: 1.5 Enable and start keepalive
  systemd:
    name: keepalived
    state: started
    enabled: yes

