---
- name: 2.1 install haproxy
  apt:
    name:
      - haproxy
      - socat
    state: present
  when: ansible_os_family == "Debian"
  notify: haproxy_restart

- name: 2.2 copy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root
    backup: true
  notify: haproxy_reload

- name: 2.3 DH2048
  community.crypto.openssl_dhparam:
  #openssl_dhparam:
    path: /etc/haproxy/dhparams.pem
    size: 2048
#  command: openssl dhparam -out /etc/haproxy/dhparams.pem 2048


