---
- name: 3.1 install pacemaker
  apt:
    name:
      - haproxy
      - socat
    state: present
  notify: haproxy_restart
  when: 
  - ansible_os_family == "Debian"
  - haproxy_install == "true"

- name: 3.2 copy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: root
    group: root
    backup: true
  notify: haproxy_reload
  when: haproxy_install == "true"
  pacemaker_install == "true"