---
- name: 3.1 OpenDJ setup
  command: su - {{ opendj_user }} -c "{{ opendj_root }}/setup
           --cli
           --baseDN {{ opendj_context }}
           --addBaseEntry
           --ldapPort {{ opendj_port_ldap }}
           --adminConnectorPort {{ opendj_port_admin }}
           --rootUserDN 'cn=Directory Manager'
           --rootUserPasswordFile {{ opendj_dm_password_file }}
           --ldapsPort {{ opendj_port_ldaps }}
           --usePkcs12keyStore {{ opendj_root }}/certs/keystore
           --keySTorePasswordFile {{ opendj_root }}/certs/keystore.pin
           --certNickname server-cert
           --hostName {{ ansible_fqdn }}
           --noPropertiesFile
           --doNotStart
           --no-prompt"
  become: true

