- name: 5.2 Set keystore for user
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig 
        set-key-manager-provider-prop
        --provider-name PKCS12
        --set key-store-file:config/keystore
        {{ dsconfig_common }}"
  become: true

- name: 5.3 Set keystore for admin
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig 
        set-key-manager-provider-prop
        --provider-name Administration
        --set key-store-type:PKCS12
        {{ dsconfig_common }}"
  become: true

