---
- name: 4.1 Copy keystores
  copy:
    src: "{{ opendj_root }}/certs/{{ item.file }}"
    dest: "{{ opendj_config }}/{{ item.file }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    mode: "{{ item.mode }}"
    remote_src: true
  become: true
  with_items:
    - { file: "keystore",           mode: '0640' }
    - { file: "truststore",         mode: '0640' }
    - { file: "truststore.pin",     mode: '0600' }
    - { file: "admin-keystore",     mode: '0640' }
    - { file: "admin-truststore",   mode: '0640' }
    - { file: "admin-keystore.pin", mode: '0600' }
    - { file: "ads-keystore",       mode: '0640' }
    - { file: "ads-keystore.pin",   mode: '0600' }

- name: 4.2 Start OpenDJ
  command: su -  {{ opendj_user }} -c "{{ opendj_bin }}/start-ds"
  become: true

- name: 4.3 Set keystore for user
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig
        set-key-manager-provider-prop
        --provider-name PKCS12
        --set key-store-file:config/keystore
        {{ dsconfig_common }}"
  become: true

- name: 4.4 Set keystore for admin
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig
        set-key-manager-provider-prop
        --provider-name Administration
        --set key-store-type:PKCS12
        {{ dsconfig_common }}"
  become: true

- name: 4.5 Set ads-truststore part 1
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig
          set-backend-prop
          --backend-name ads-truststore 
          --set trust-store-file:{{ opendj_root }}/certs/ads-truststore 
        {{ dsconfig_common }}"
  become: true

- name: 4.6 Copy ads-truststore
  copy:
    src: "{{ opendj_root }}/certs/{{ item.file }}"
    dest: "{{ opendj_config }}/{{ item.file }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    mode: "{{ item.mode }}"
    remote_src: true
  become: true
  with_items:
    - { file: "ads-truststore",     mode: '0640' }
    - { file: "ads-truststore.pin", mode: '0600' }

- name: 4.7 Set ads-truststore part 2
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig
          set-backend-prop
          --backend-name ads-truststore 
          --set trust-store-file:config/ads-truststore 
        {{ dsconfig_common }}"
  become: true

- name: 4.8 Remove certs directory
  file:
    path: "{{ opendj_root }}/certs"
    state: absent
  become: true

- name: 4.9 Restart OpenDJ
  command: su -  {{ opendj_user }} -c "{{ opendj_bin }}/stop-ds --restart"
  become: true

