---
- name: 4.1 Copy keystores into OpenDJ config directory
  copy:
    src: "{{ opendj_root }}/certs/{{ item.file }}"
    dest: "{{  opendj_config  }}"
    owner: "{{ opendj_user }}"
    group: "{{ opendj_group }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
      - { file: "keystore", mode: '0640' }
      - { file: "truststore", mode: '0640' }
      - { file: "admin-keystore", mode: '0640' }
      - { file: "admin-truststore", mode: '0640' }
      - { file: "admin-keystore.pin", mode: '0600' }
      - { file: "truststore.pin", mode: '0600' }
  become: true

- name: 4.2 Set keystore for user
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig 
        set-key-manager-provider-prop
        --provider-name PKCS12
        --set key-store-file:config/keystore
        {{ dsconfig_common }}"
  become: true

- name: 4.3 Set keystore for admin
  command: su - {{ opendj_user }} -c "{{opendj_bin }}/dsconfig 
        set-key-manager-provider-prop
        --provider-name Administration
        --set key-store-type:PKCS12
        {{ dsconfig_common }}"
  become: true

