---
- name: 1.1 Install keepalived on Ubuntu
  apt:
    name: keepalived
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: 1.1 Install keepalived on Oracle Linux
  yum:
    name: keepalived
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: 1.2  set ip_nonlocal_bind in sysctl.conf
  shell: echo "net.ipv4.ip_nonlocal_bind=1" >> /etc/sysctl.conf
  become: true

- name: 1.3 sysctl -p
  command: sysctl -p
  become: true

- name: 1.4 Copy keepalive.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    owner: root
    group: root
  become: true

- name: 1.5.1 Open port 112 in firewall in Ubuntu
  ufw:
    rule: allow
    src: 224.0.0.18
  become: true
  when: ansible_os_family == "Debian"

- name: 1.5.2 Open port 112 in firewall in Ubuntu
  ufw:
    rule: allow
    dest: 224.0.0.18
  become: true
  when: ansible_os_family == "Debian"

- name: 1.5 Open port 112 in firewall in OracleLinux
  firewalld:
    rich_rule: rule protocol value="vrrp" accept
    permanent: yes
    immediate: yes
    state: enabled
  become: true
  when: ansible_os_family == "RedHat"

- name: 1.6 Enable and start keepalive
  systemd:
    name: keepalived
    state: started
    enabled: yes
  become: true

