# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: NetworkManager
#  ethernets:
#    enp1s0:
#      addresses:
#      - 192.168.0.167/24
#      gateway4: 192.168.0.1
#      nameservers:
#        addresses:
#        - 192.168.0.163
#        - 192.168.0.171
#        search: []
